fix: modified intercept for ieee8021xconfigs
open-amt-cloud-toolkit/sample-web-ui pull request #1085
Opened 2023-04-11 21:46 UTC by Walt-Intel

## PR Checklist

- [ ] Unit Tests have been added for new changes
- [ ] API tests have been updated if applicable
- [ ] All commented code has been removed
- [ ] If you've added a dependency, you've ensured license is compatible with Apache 2.0 and clearly outlined the added dependency.

## What are you changing?

## Anything the reviewer should know when reviewing this PR?

### If the there are associated PRs in other repositories, please link them here (i.e. open-amt-cloud-toolkit/repo#365 )

2023-06-07 16:55 UTC, rsdmike requested changes

2023-06-07 16:55 UTC, rsdmike commented on cypress/e2e/integration/profile/create.spec.ts
> +    // api8021x
remove commented code

2023-06-07 16:55 UTC, rsdmike commented on cypress/e2e/integration/wireless/create.spec.ts
> +    // cy.wait('@wirelessconfigsGetAll')
remove if not using

2023-06-08 21:41 UTC, Walt-Intel commented on cypress/e2e/integration/wireless/create.spec.ts
> +    // cy.wait('@wirelessconfigsGetAll')
removed

2023-06-09 20:16 UTC, rsdmike approved these changes

2023-06-09 22:18 UTC, merged