feat(authentication): added stateless authentication
open-amt-cloud-toolkit/sample-web-ui pull request #162
Opened 2021-04-05 18:08 UTC by madhavilosetty-intel

2021-04-05 23:31 UTC, rsdmike requested changes

2021-04-05 23:31 UTC, rsdmike commented on src/app/auth.service.ts
> +  getLoggedUserToken (): any {
string return type

2021-04-05 23:31 UTC, rsdmike commented on src/app/custom.interceptor.ts
> +              this.authService.logout()
use `Router` to redirect to /login route

2021-04-08 22:47 UTC, rsdmike requested changes

2021-04-08 22:47 UTC, rsdmike commented on src/app/app.module.ts
> +    DialogcontentComponent
change to `DialogContentComponent`

2021-04-08 22:47 UTC, rsdmike commented on src/app/shared/dialogcontent/dialogcontent.component.html
> +    <button mat-button mat-dialog-close="false">ok</button>
lets capital OK here

2021-04-08 23:02 UTC, madhavilosetty-intel commented on src/app/app.module.ts
> +    DialogcontentComponent
done

2021-04-08 23:02 UTC, madhavilosetty-intel commented on src/app/shared/dialogcontent/dialogcontent.component.html
> +    <button mat-button mat-dialog-close="false">ok</button>
done

2021-04-09 21:25 UTC, rsdmike approved these changes

2021-04-09 21:34 UTC, merged