refactor: moves explorer to device detail page
open-amt-cloud-toolkit/sample-web-ui pull request #2040
Opened 2024-07-22 15:40 UTC by matt-primrose

## PR Checklist

- [ ] Unit Tests have been added for new changes
- [ ] API tests have been updated if applicable
- [ ] All commented code has been removed
- [ ] If you've added a dependency, you've ensured license is compatible with Apache 2.0 and clearly outlined the added dependency.

## What are you changing?

## Anything the reviewer should know when reviewing this PR?

### If the there are associated PRs in other repositories, please link them here (i.e. open-amt-cloud-toolkit/repo#365 )

2024-07-22 16:58 UTC, rsdmike requested changes
missing condition for cloudmode

2024-07-22 17:11 UTC, rsdmike commented on src/app/explorer/explorer.component.ts
> +        this.devicesService.executeExplorerCall(this.deviceId, this.selectedWsmanOperation).subscribe((data) => {
missing error handler snackbar message

2024-07-22 17:11 UTC, rsdmike commented on src/app/explorer/explorer.component.ts
> +    this.devicesService.executeExplorerCall(this.deviceId, this.selectedWsmanOperation).subscribe((data) => {
missing error handler snackbar message

2024-07-22 20:29 UTC, matt-primrose commented on src/app/explorer/explorer.component.ts
> +        this.devicesService.executeExplorerCall(this.deviceId, this.selectedWsmanOperation).subscribe((data) => {
added error handler

2024-07-22 20:29 UTC, matt-primrose commented on src/app/explorer/explorer.component.ts
> +    this.devicesService.executeExplorerCall(this.deviceId, this.selectedWsmanOperation).subscribe((data) => {
added error handler

2024-07-22 23:33 UTC, rsdmike approved these changes

2024-07-22 23:37 UTC, merged

2024-07-25 21:27 UTC, RosieAMT commented
:tada: This PR is included in version 3.12.2 :tada:

The release is available on:
- [GitHub release](https://github.com/open-amt-cloud-toolkit/sample-web-ui/releases/tag/v3.12.2)
- `v3.12.2`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: