fix: resolves handling when when amt redirection features are available
open-amt-cloud-toolkit/sample-web-ui pull request #2202
Opened 2024-09-19 14:19 UTC by matt-primrose

## PR Checklist

- [ ] Unit Tests have been added for new changes
- [ ] API tests have been updated if applicable
- [ ] All commented code has been removed
- [ ] If you've added a dependency, you've ensured license is compatible with Apache 2.0 and clearly outlined the added dependency.

## What are you changing?

## Anything the reviewer should know when reviewing this PR?

### If the there are associated PRs in other repositories, please link them here (i.e. open-amt-cloud-toolkit/repo#365 )

2024-09-19 16:29 UTC, rsdmike requested changes

2024-09-19 16:29 UTC, rsdmike commented on src/app/devices/general/general.component.ts
> +        if (!this.cloudMode) {
i think can reduce the condition down to just setting disabled property for kvm ? kind of like line 106

2024-09-19 21:59 UTC, graikhel-intel submitted a review, later dismissed

2024-09-20 16:35 UTC, rsdmike requested changes
Nice try captain

2024-09-20 20:22 UTC, madhavilosetty-intel approved these changes

2024-09-20 21:33 UTC, rsdmike approved these changes

2024-09-20 21:33 UTC, merged

2024-09-20 21:36 UTC, RosieAMT commented
:tada: This PR is included in version 3.20.5 :tada:

The release is available on:
- [GitHub release](https://github.com/open-amt-cloud-toolkit/sample-web-ui/releases/tag/v3.20.5)
- `v3.20.5`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: