feat(paging): implemented paging for cira, domains, devices, profiles and wifi
open-amt-cloud-toolkit/sample-web-ui pull request #370
Opened 2021-08-09 03:39 UTC by Mahendra-intel

2021-08-12 23:49 UTC, rsdmike requested changes
Looking good, just need to minimize the anys

2021-08-12 23:49 UTC, rsdmike commented on src/app/devices/devices.service.ts
> +  getDevices (pageSize: any, startsFrom: any, count: any, tags: string[] = []): Observable<DeviceResponse> {
we can type these

2021-08-12 23:49 UTC, rsdmike commented on src/app/configs/configs.component.ts
> +  pageChanged (event: any): void {
can we type this?

2021-08-13 16:20 UTC, Mahendra-intel commented on src/app/devices/devices.service.ts
> +  getDevices (pageSize: any, startsFrom: any, count: any, tags: string[] = []): Observable<DeviceResponse> {
resolved

2021-08-13 16:20 UTC, Mahendra-intel commented on src/app/configs/configs.component.ts
> +  pageChanged (event: any): void {
resolved

2021-08-19 14:53 UTC, rsdmike approved these changes

2021-08-20 20:50 UTC, merged