feat(ciraconfig): allow clearing out cira config in profile
open-amt-cloud-toolkit/sample-web-ui pull request #382
Opened 2021-08-17 13:01 UTC by chethanbellechalu-intel

closes #367

2021-08-18 04:05 UTC, rsdmike requested changes

2021-08-18 04:05 UTC, rsdmike commented on src/app/profiles/profile-detail/profile-detail.component.ts
> +      console.info('results', result)
remove

2021-08-18 15:12 UTC, chethanbellechalu-intel commented on src/app/profiles/profile-detail/profile-detail.component.ts
> +      console.info('results', result)
done

2021-08-19 14:56 UTC, rsdmike approved these changes

2021-08-19 15:22 UTC, merged