feat(login): MPS web_auth_enabled set to false, sample web ui cannot be
open-amt-cloud-toolkit/sample-web-ui pull request #656
Opened 2022-05-03 17:09 UTC by madhavilosetty-intel

accessed.

AB#7073

## PR Checklist

- [ ] Unit Tests have been added for new changes
- [ ] API tests have been updated if applicable
- [ ] All commented code has been removed
- [ ] If you've added a dependency, you've ensured license is compatible with Apache 2.0 and clearly outlined the added dependency.

## What are you changing?

## Anything the reviewer should know when reviewing this PR?

### If the there are associated PRs in other repositories, please link them here (i.e. open-amt-cloud-toolkit/repo#365 )

2022-05-03 21:02 UTC, matt-primrose commented on src/app/login/login.component.ts
> +            this.snackBar.open($localize`${err.error.message}`, undefined, SnackbarDefaults.defaultError)
Can we add tests for these conditions?

2022-05-03 21:03 UTC, matt-primrose requested changes
add test coverage for the err.status === 405 condition statement

2022-05-23 16:28 UTC, madhavilosetty-intel commented on src/app/login/login.component.ts
> +            this.snackBar.open($localize`${err.error.message}`, undefined, SnackbarDefaults.defaultError)
done

2022-05-24 16:14 UTC, rsdmike approved these changes

2022-05-24 16:25 UTC, matt-primrose approved these changes

2022-05-24 16:25 UTC, merged